### ISSUE TITLE
Fix localization on Windows

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#19]
`locale.bindtextdomain` is not available on Windows.

I would like to find something better than 4d91b7452c1adc30aecfcf0df483523a5565516e so we don't disable localization.

May be <https://stackoverflow.com/a/8377533> could help.

Ref #16 #11

**Comment by jeromerobert** [comment]
Notifying  @carlos22 as he is the first one to have worked on this issue.

**Comment by jeromerobert** [comment]
Looping on all widget looks to change their labels with their `gettext` translation seems clever but also hacky. I'll commit the libintl solution soon, but I don't mind having both in the repo so we could test them.

**Comment by jeromerobert** [comment]
I tried https://gitlab.gnome.org/GNOME/meld/blob/master/bin/meld#L114 with no luck. I get no error message and no `Gtk.Builder` translation.

**Comment by carlos22** [comment]
Hmm same for me. Not sure why. The pympress people did the same before the above linked change: https://github.com/Cimbali/pympress/pull/21/files#diff-e41eead59a5b8d11220101c32c3cf0a8L184 - not sure why they don't need to load it afterwards. I think it is because of the looping which seems to be less hacky than loading a dll?! Because after your changes (or even before?) Some parts of the app get translated, but not all (Save becomes Speichern for example).
