### ISSUE TITLE
Adding pdfarranger in Linux Mint/Ubuntu/Debian repositories

### ISSUE THREAD

**Issue by InfoLibre** [jeromerobert/pdfarranger#192]

**Comment by dreua** [comment]
@InfoLibre Did you reopen this issue intentionally?

**Comment by InfoLibre** [comment]
Sorry. I wanted to ask if pdfarranger could use MuPDF to have a better rendering than with PDF-Shuffler. But I tested pdfarranger and it works fine now, rendering is better. So I close this issue.

**Comment by dreua** [comment]
No worries, it was just confusing that this issue was open but it seemed like you wanted to close it. I guess your reopened it by accident. I'm happy to hear that pdfarranger works fine for you :smiley:

**Comment by InfoLibre** [comment]
Yes, I'm using it on Linux Mint MATE. It would be great if the package was added to the Linux Mint repository.

**Comment by dreua** [comment]
Which version of Mint are you using and is it the Debian or the Ubuntu based version? (You can try `lsb_release -a`)
In general, packaging is done by your Linux distribution (i.e. Mint), this repository's main purpose is only the development and distribution of the source code. I had a quick look and in Mint's special case it seems like it is consuming packages from Debian or Ubuntu and they do have pdfarranger packages at least in some versions so that is a bit unclear. Still the Mint support/forums/mailinglist are your best bet for finding a solution.

(We do have an exe for Windows, [flatpak](https://flathub.org/apps/details/com.github.jeromerobert.pdfarranger) and I personally also maintain packages for Fedora because that is what I use myself.)

**Comment by InfoLibre** [comment]
Linux Mint Debian Edition (LMDE) repository is based on debian repository. Other editions (MATE edition, Cinnamon edition...) are using repository based on Ubuntu repository. I'm using Linux Mint MATE edition and I did not found pdfarranger in it. I added the PPA.
I opened an issue : https://github.com/linuxmint/linuxmint/issues/245

**Comment by dreua** [comment]
[According to Wikipedia](https://en.wikipedia.org/wiki/Linux_Mint_version_history#Release_history) Mint 19.3 Tricia is based on Ubuntu 18.04 which does not have pdfarranger in it's repository [according to repology](https://repology.org/project/pdfarranger/versions).

Searching a bit I saw this thread/post which might be interesting for you: [Linux mint forums - how to request package updates](https://forums.linuxmint.com/viewtopic.php?p=1752424&sid=fd452ee543859e42b509aad8b1464bf9#p1752424)

**Comment by InfoLibre** [comment]
I renamed this issue and re-opened it.

**Comment by dreua** [comment]
Please have a look at repology: https://repology.org/project/pdfarranger/versions

You will see that pdfarranger is in Ubuntu/Debian but not in the particular version your mint is based on and there is nothing we can do about it here. Therefore I would suggest you remove Ubuntu/Debian from the title and keep this issue closed.

**Comment by InfoLibre** [comment]
Thank you for this information.
