### ISSUE TITLE
Can't open cropped file in Acrobat Reader

### ISSUE THREAD

**Issue by jcrows** [jeromerobert/pdfarranger#198]
Files cropped with pdfarranger cannot be opened in Acrobat Reader on Windows 10
They open without any trouble in a web browser, but show up as a blank page in Acrobat.
See below for an example file.

[pdfarranger example.pdf](https://github.com/jeromerobert/pdfarranger/files/4596214/pdfarranger.example.pdf)

**Comment by jcrows** [comment]
If I change the display resolution in preferences and close the document it presents the following error:
"There was a problem reading this document (14)"
Control clicking on "OK" gives:
"Expected a dict object."

**Comment by dreua** [comment]
That is certainly strange, never heard of problems like this. Reproducible with all PDFs I tried on Adobe Acrobat DC 20.006.20042. 
Not reproducible on all other PDF viewers I tried on Windows (including Firefox, Edge, Chrome, Foxit Reader) and Linux.
![Acrobat Error](https://user-images.githubusercontent.com/15114715/81385552-ce505a00-9113-11ea-8309-b5f7f3786cd7.png) \
(My Windows is actually set to english but Acrobat reader doesn't respect that :unamused: )

Holding down Ctrl while clicking Ok like explained in the [first google result](https://community.adobe.com/t5/acrobat-reader/there-was-a-problem-reading-this-document-14/td-p/9208676?page=1) yields me the same information as in that thread: "Expected a dict object." (Translated from german ofc.)

Also [in this thread](https://community.adobe.com/t5/acrobat-reader/there-was-a-problem-reading-this-document-14/m-p/10924989#M63187) the question arises whether this is a Acrobat bug or not...

I'll try reproducing with qpdf cli and pikepdf in that order to narrow it down.

**Comment by mimi89999** [comment]
Works in Evince on Debian.

**Comment by dreua** [comment]
Yes, this is 99% an Acrobat Reader bug. I'm working on the details, sorry for taking so long...

**Comment by dreua** [comment]
Thank you for your patience everyone, I was worried that this could reveal a security issue in Acrobat and therefore did some digging which I didn't want to share earlier. Today Adobe PSIRT informed me that it is not a security issue but "an implementation level limitation" so here we go:

Probably due to some rounding errors, pdfarranger produces really long floating point numbers for the page dimensions when cropping (more than 19 decimal places after the comma). Pikepdf writes these into the PDF and Acrobat is not able to handle them.

The [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) says about values of type "real", that "Number of significant decimal digits of precision in fractional part (approximate)" is 5 (p. 650). I would not consider that a hard limit so we are arguably within spec, but more than 20 digits is definitely overkill. As Adobe didn't state if or when they are going to fix it, I'd say we round it to maybe 15 digits or less in pdfarranger or pikepdf.

@jbarlow83 how do you think of handling this in pikepdf?


PS: Here are some files I crafted during my investigation, just in case someone is interested. Filename "x.y" means x digits before and y after the comma. For the last two I didn't care to count, but they do produce interesting results.
[2.19.pdf](https://github.com/jeromerobert/pdfarranger/files/4788546/2.19.pdf)
[2.20.pdf](https://github.com/jeromerobert/pdfarranger/files/4788548/2.20.pdf)
[3.19.pdf](https://github.com/jeromerobert/pdfarranger/files/4788549/3.19.pdf)
[3.20.pdf](https://github.com/jeromerobert/pdfarranger/files/4788550/3.20.pdf)
[mediumLongFloat.pdf](https://github.com/jeromerobert/pdfarranger/files/4788551/mediumLongFloat.pdf)
[veryLongFloat.pdf](https://github.com/jeromerobert/pdfarranger/files/4788552/veryLongFloat.pdf)

**Comment by jbarlow83** [comment]
Seems to be a consequence of certain operations that when done in `Decimal` or converted from `float`, cause `Decimal` objects with excessive precision.

I'll fix this. There are other ways to produce it outside of pdfarranger, and producing a PDF that doesn't work in Acrobat doesn't seem ideal. Went with 15 digits of precision.

**Comment by dreua** [comment]
Great, thank you!
Today I learnt that python's [decimal](https://docs.python.org/3.8/library/decimal.html) is actually meant for exact arithmetic in the decimal (i.e. base 10) system while I knew from my computer science studies that floats are working on in the base 2 system which causes all kinds of rounding issues (e.g. `1.1 + 2.2 = 3.3000000000000003`). Conversion between the two systems explains the excessive precision we see here.

**Comment by dreua** [comment]
Fixed with pikepdf 1.15.1, I just tested with the [update in Fedora 32 testing](https://bodhi.fedoraproject.org/updates/FEDORA-2020-78daeab21c) and updated the Flatpak - both work as expected. :smiley: 
@jcrows you may need to convince your distribution's pikepdf maintainer to issue an update, install pikepdf via pip or go directly for the pdfarranger flatpak. 

I believe this is all we can do her and this issue can be closed, thanks for bringing it to our attention!

**Comment by jeromerobert** [comment]
I'll ensure to get pikepdf 1.15.1 in the 1.6.0 pdfarranger Windows bundle.
