### ISSUE TITLE
No images of pages

### ISSUE THREAD

**Issue by N7DR** [jeromerobert/pdfarranger#215]
I just installed the current debian stable package (version 1.1.1) and, unlike prior versions, when I add/open a PDF file, I don't see any of the actual contents of the pages.

Here is a screenshot of what I'm seeing (I hope):
 
![bug-report](https://user-images.githubusercontent.com/6434203/85451825-8072a280-b557-11ea-8741-c0251e6fedfd.png)

**Comment by dreua** [comment]
### About Debian Stable / v1.1.1
First of all, 1.1.1 is quite old tbh. There has been a lot of development going on in the meantime, adding features and also fixing bugs that you might still hit with that version. (But off the top of my head I'd say this issue is not one of them.) I guess that is just a thing with Debian stable but do let us know if you think something on our side could be done to achieve more updates to Debian packages. And maybe consider using something more recent, we have a flatpak or you could install via pip. (Btw: Wow, I just checked and even Debian unstable is quite old.)

### Your actual issue
To debug your issue I need some information:
1. Does this happen with one specific PDF or with all PDFs? (I guess the latter, but please try at least one PDF from another source to be sure.)
2. Could you run `pdfarranger` from the command line and see if there is any output that could help us?
3. What is the version of your Debian? (Run `lsb_release -a` if not sure.)

### Flatpak as workaround?
I personally prefer up to date native packages but in your case maybe using [the Flatpak](https://flathub.org/apps/details/com.github.jeromerobert.pdfarranger) is the easiest way to fix this and get a recent version of pdfarranger and pikepdf. (pikepdf is the pdf library behind pdfarranger and is updated even more frequently, most recently to fix #198)

**Comment by dreua** [comment]
Okay, never mind my questions, I got curios and started a virtual machine - could you install `python3-gi-cairo` and tell me that it fixes your issue?

**Comment by N7DR** [comment]
David Auer wrote on 6/23/20 3:17 PM:
> Okay, never mind my questions, I got curios and started a virtual machine - could you install `python3-gi-cairo` and tell me that it fixes your issue?
> 

Yep, that's it. Wonderful. Thank you.

I was going to mention that this had the feel that it was more likely a debian
packaging issue than a real programming issue, but I didn't want to presuppose
the result :-)

I shall file a bug report against debian stable, and tell them the fix.

  Doc

-- 
Web:  http://enginehousebooks.com/drevans

**Comment by N7DR** [comment]
D. R. Evans wrote on 6/23/20 3:47 PM:

> 
> I shall file a bug report against debian stable, and tell them the fix.

The bug was already filed and fixed... but not in debian stable :-( It's
always annoying when that happens. My experience is that it's pretty random
whether the fix is included in the next dot release of debian stable.

  Doc

-- 
Web:  http://enginehousebooks.com/drevans

**Comment by dreua** [comment]
Oh well that's unfortunate but thanks for looking it up anyway.  I don't know about the Debian update policy but please do tell me if you ever find a good reason behind this ;)

Feel free to post a link to the Debian issue here in case someone else needs it. And for this issue, since it turned out to be distribution specific, maybe you could prefix the title with "Debian", thanks!

(OT: There are distributions with other update policies, I for example am quite happy with my Fedora.)

**Comment by N7DR** [comment]
David Auer wrote on 6/23/20 4:53 PM:
> Oh well that's unfortunate but thanks for looking it up anyway.  I don't know about the Debian update policy but please do tell me if you ever find a good reason behind this ;)

The basic idea seems to be that "stable" should be... "stable", so nothing
gets updated except for security fixes. Except that that's manifestly not
true. In general, though, it does seem to be be that "mere" bugfixes don't
make it into updates of stable.

> 
> Feel free to post a link to the Debian issue here in case someone else needs it. And for this issue, since it turned out to be distribution specific, maybe you could prefix the title with "Debian", thanks!

It's debian bug 954033:
  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954033
There it says that the fix has been applied to unstable, so it probably won't
trickle down to stable until stable itself moves upwards to meet it with the
next major version release.

> 
> (OT: There are distributions with other update policies, I for example am quite happy with my Fedora.)
> 

I've lost count of the different distros I've used over the years. I finally
reached the point of being fed up with life being too bleeding edge, so went
to debian stable three or four years ago. Life between version upgrades does
seem much smoother (but I haven't found upgrades to be noticeably less traumatic).

  Doc

-- 
Web:  http://enginehousebooks.com/drevans
