### ISSUE TITLE
Drop python 2 support after the next release

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#22]
This issue is to survey the community about dropping the python 2 support. My intention is to keep python 2 compatibility until the next release, then to only ensure python 3 after. If it's not good for you please, give arguments.

**Comment by dreua** [comment]
For me as a developer earlier dropping of python 2 is better, because we can write cleaner code and less testing with python 2, but if you want to keep compatibility that's fine. It also depends on how/when you plan the next release, for example if fixing #17 turns out to be particulary hard or ugly with python 2 in mind this might change things a bit.

**Comment by jeromerobert** [comment]
>  It also depends on how/when you plan the next release

I want to release before the end of the year, mostly because distros are waiting for python 3 support. To me, the only critical task is the rebranding. #17 and windows support are currently the 2 level 2 priority tasks. If they can be in the next release that will be nice, if they can't, no matter, they'll be in the one after.
I'll update the milestones in all open issues soon.

> for example if fixing #17 turns out to be particulary hard or ugly with python 2

Do you have elements that let you think that is the case ? or is this a random example ?

**Comment by dreua** [comment]
Its just a random example. Your plan sounds good to me, looking forward remove my favorite PDF tool from the python 2 packages left in Fedora!
