### ISSUE TITLE
Change 'select odd/even pages' to work on absolute page numbers

### ISSUE THREAD

**Issue by angsch** [jeromerobert/pdfarranger#261]
Hi,

After duplicating/splitting a page, the page number associated with the page is copied. To reproduce: Import a pdf with a single page, select duplicate (or split). The figure below illustrates the issue.
![image](https://user-images.githubusercontent.com/17718454/90129858-b408c680-dd69-11ea-8914-02f31f65f22a.png)

In my opinion it makes sense to update the page number. Consider that a user wants to split scanned book pages, select all odd pages and then export these. With the current page numbering, _all_ pages will be selected through 'Select odd pages'.

Best,
angsch

**Comment by dreua** [comment]
Like I understand it, the displayed page number is that of the originally imported PDF so what you see in the screenshot would make sense. (If you import multiple PDFs with many pages, this information is more useful than with just one duplicated page in your case.) So either that logic needs to be changed so that the displayed page number always follows the displayed order in pdfarranger or we need to change "Select odd pages" to select every second page in displayed order and ignore the page numbers. Intuitively I'd say the latter is the easier and better fix. If we go that route, we should consider renaming the command, too.

Additionally, I'm not against re-numbering pages after they have been split but I think that the issue with selection should be addressed at a higher level. (This problem would not only occur with duplicated or split pages but also when a single page is removed replaced etc.)

**Comment by angsch** [comment]
Good point. Based on the name, I would expect the selection functions ('select odd pages'/'select even pages') to refer to the global page numbers and not to document-local page numbers. So personally I do not see the need to rename the select functions.

**Comment by dreua** [comment]
Alright, so only change to be done is make "select odd/even pages" work on the page numbers as ordered in pdfarranger, not the original / displayed page numbers? (I'd be +1 for that.)

**Comment by angsch** [comment]
@dreua Thanks, I changed the title for clarification.

Here are two examples that illustrate the suggested modification.

Example 1.
Import a pdf with a single page and split it. 'Select odd pages' selects a single page (out of 2 pages in total), namely the first.

Example 2.
Import two pdfs with a single page each, select all and split. 'Select even pages' selects two pages, the second and the fourth, (out of 4 pages in total).

**Comment by dreua** [comment]
I actually haven't tested the select even/odd yet, will it always work on all available pages or can you apply it to a selection as well?

**Comment by kbengs** [comment]
I also agree with you, I think..  It's still somewhat odd, as it wouldn't necessarily select odd page numbers although that was what you chose to do.. Would a "update page numbers" action be something to consider? It could be useful in other situations too. The imported page numbers can be valuable information when rearranging pages so I think they should not just be replaced with global page numbers.

@dreua It will always work on all pages regardless what is selected.

**Comment by dreua** [comment]
I'm not sure users will understand what this action is for and remember to use it when they need it.
How about a page number display of the last selected page instead, like in evince? (Showing page x of y in the top left instead of just y.) If we want to make it extra fancy, it could even show selections of multiple pages ("1, 5, 99 of 100", "1-100 of 100" etc.) and double it as an input (insert 2-22) to select those pages... Well these are just some ideas, not sure if it is worth our time really. But just showing the last focused page (ignoring selections of multiple pages for now) could be helpful imo, what do you think?

**Comment by jeromerobert** [comment]
We could show the current selection in the top bar (next too the total page number), but that's for an other issue. For that issue I think we just need:
```patch
--- a/pdfarranger/pdfarranger.py
+++ b/pdfarranger/pdfarranger.py
@@ -1127,15 +1127,13 @@ class PdfArranger(Gtk.Application):
         elif selectoption == 'DESELECT':
             self.iconview.unselect_all()
         elif selectoption == 'ODD':
-            for row in model:
-                page_number = row[3]
+            for page_number, row in enumerate(model):
                 if page_number % 2:
                     self.iconview.select_path(row.path)
                 else:
                     self.iconview.unselect_path(row.path)
         elif selectoption == 'EVEN':
-            for row in model:
-                page_number = row[3]
+            for page_number, row in enumerate(model):
                 if page_number % 2:
                     self.iconview.unselect_path(row.path)
                 else:
```
@kbengs Do you agree with that ?

**Comment by kbengs** [comment]
Yes I agree on both to show selection in top bar and to fix this issue. (start=1 also needs to be added) Do you fix this commit Jerome or shall I?
