### ISSUE TITLE
Zooming does not re-render file

### ISSUE THREAD

**Issue by madduck** [jeromerobert/pdfarranger#53]
If I zoom in on a file, it seems as if the thumbnail is blown up, but not actually recomputed, causing rather blurred pages.

**Comment by logari81** [comment]
Just to add some background information on this. Re-rendering and lazy rendering weren't implemented/enabled in pdfshuffler because of a memory leak in the python bindings of poppler, which I had reported ~5 years ago. Especially with the transition to gtk3 I assume that the bug is fixed, hence one could finish the partly implemented lazy rendering and rerendering.

**Comment by madduck** [comment]
Thank you for this info, and all your work!

-- 
@martinkrafft | https://riot.im/app/#/room/#madduck:madduck.net
 
the reason that every major university
maintains a department of mathematics
is that it's cheaper than
institutionalizing all those people.
 
spamtraps: madduck.bogus@madduck.net
