### ISSUE TITLE
default save and replace original file

### ISSUE THREAD

**Issue by giannino** [jeromerobert/pdfarranger#65]
I wish it could behave like all file modifiers: upon closing should warns about replacing the original file and save the modified file.
using ubuntu 19.04, could be realted to file attributes?

**Comment by jeromerobert** [comment]
It does not because pdfarranger is not rigorously a file modifier. The PyPDF2 import/export is not a transparent operation. If you add a PDF file to pdfarranger then save, PyPDF2 rewrite the whole file and possibly change it's structure. Most of the time we don't want the original file to be replaced because there is a high risk of data loss.

This is why the *save* action redirect to *save as* until the user has specified a file name to save to.

Here is what I suggest:

* if a single file (or no file) was imported and not modified
     * Quietly close
* else ask about save confirmation, and if yes
     * if the user as already manually run the *save* or *save as* action to select a different file name
          * Quietly save and close
     * else
          * Open a *save as* dialog

The implementation is linked to #59 because this is where I can get the modified status of the file.

**Comment by giannino** [comment]
What you show it's the implementation already in place, so why not add an
other option _with warning of data loss_ or , even better, creating a
backup copy of the original file?
I guess that 99& of the times the common user discard the original file, I
use mostly for deleting pages.

Thanks for your help

**Comment by dreua** [comment]
How is the risk of data loss addressed with this solution? I think it's rather serious since the exported file can be corrupted while the preview in pfarranger looks good. The user has no possibility to check the results before it's too late

**Comment by jeromerobert** [comment]
@dreua I did not implemented what OP asked for. A file chooser still popup at the first save, but now it default to the first imported PDF files. So before overwriting a file the user still have to confirm two times:
* Click save in the file chooser without changing the file name
* Confirm that he wants to overwrite

He can also blindly press `ctrl+s`, `enter`, `enter` which allow to get almost what OP wants.

**Comment by dreua** [comment]
That sounds okay to me, thank you for the clarification!

**Comment by madduck** [comment]
For me, the "save" dialog does not default to a filename, unfortunately. If it did that, I guess I could live with it (and #100 could be ignored).

Also, how do you get `ctrl+s` to work?

**Comment by dreua** [comment]
@madduck For me the "save" dialog always defaults to a filename (pdfarranger 1.3.0) and `ctrl+s` just works. Unfortunately I can only look into your problem if there is a way for me to reproduce it.

**Comment by petaflot** [comment]
`ctrl+s enter enter` does not work due to window focus issues and because I don't want my move to jump to new dialogs (high risk of bad clicks).

for the risk of data loss, there's a thing called "using a temporary filename".

if you refuse to implement this, I will fork.

**Comment by madduck** [comment]
@petaflot it would be cool if you submitted a merge request. Also starts with a fork. ;)

**Comment by petaflot** [comment]
I'm looking at the code.

I figured "to make everyone happy, I'll add a "ctrl+alt+s shortcut". That doesn't make _me_ happy:

WTF is this `<Primary>` name for `ctrl`? comments says "See ..." for list of keys", "Primary" is not in the list. Come on... am I supposed to try pseudo-random names to find out the correct binding?

**Comment by petaflot** [comment]
`<Secondary>` is obviously not recognized. Unless someone gives me a clue, I will just write a dirty hack that I will keep for myself instead of doing things properly

**Comment by petaflot** [comment]
days until I make my own distro: `current_days_count -1`

**Comment by n0body-special** [comment]
I really don't understand why the developer cares about the safety of our files more than we do. 99,9% of times I just want to rotate 90 degrees or remove a blank page. No, I don't want to keep the original file. If I click "save", it's because I want the original file gone, else I would have clicked "save as", which is also a choice.

All these years, I am forced to choose save, select the same file and overwrite it, so if the file is going to be corrupted, I will overwrite the original anyway. I really don't understand this whole "for your own safety" mindset. This is the only program in the world that drastically changes such a fundamental function which has existed for ages in the history of computers.
