### ISSUE TITLE
Merge double sided scanned document

### ISSUE THREAD

**Issue by loxK** [jeromerobert/pdfarranger#67]
I often have to scan double sided documents. I scan one side then the other. Finnally I merge them using PDFSam which has the functionality to properly arrange double sided documents on merge.

I'd rather use pdfarranger for that task.

**Comment by jeromerobert** [comment]
What do you mean by "properly arrange double sided documents on merge" ?

**Comment by loxK** [comment]
Having a double sided document of multiple pages:
- you scan one side of all pages to a PDF document
- you scan the other side of all pages to another PDF document
- you merge them with an app and have the pages properly ordered (first page doc one, then first page doc two, second page doc one, then second page doc two and so on)

**Comment by dreua** [comment]
The logic sounds easy enough. More important question imo is the user interface. I am just thinking about an "Add interleaved" option where you add a new PDF and set that pages should be inserted at every 2nd (3rd, 4th if there is a use case for that) position in the current buffer starting at position 0, 1, ... 

But actually a dedicated "Merge double sided" wizard might be more appropriate and easier to use.

**Comment by dreua** [comment]
Now I'm curious how PDFSam does the UI..

**Comment by loxK** [comment]
I can only show it in french, but PDFsam basic is free (not open source). The UI is rather simple.

![image](https://user-images.githubusercontent.com/136687/57753115-f393cd80-7736-11e9-94a9-8fb0eeeb3f02.png)

**Comment by jeromerobert** [comment]
@dreua I would prefer not to have a GUI for that feature. I think that having an interleave action would be enough. It should take the current selection into account and work on all pages if nothing is selected. I would like to do the undo/redo refactoring (#59) **before** we (you ?) work on this issue to void conflicts.

**Comment by dreua** [comment]
Yes, waiting for the undo/redo makes sense, thanks for the reminder! To be honest, I'm not sure if I will have the time to work on this, but I might. 

@loxK Here is a [simple command line python script for the purpose](https://gist.github.com/dreua/04d69e3f3f8c9ac3fc91063bf0fe4309), in case that helps you in the meantime.

**Comment by dreua** [comment]
Oh and for the UX: 

Are you planning to include selection in the undo/redo? (I.e. selection of multiple pages is restored after a "interleave" action is undone. Might be very useful if users need a second try to get the "which of my interleaved ranges becomes the first page"-problem fixed.)

My current idea for a user story would be:
1) User adds both pdf files in pdfarranger, either via command line argument, file open action or drag and drop (pdf file from file manager or pages from other pdfarranger instance). [Nothing to be done here, just for completeness sake.]
2) User selects a range of pages, either the front sides or the back sides (usually this would be one of the files but I would not like to add restrictions here) [Done, dito.]
3) User has two actions in the context or Edit menu: "Interleave (first)" or "Interleave (second)"
4) The selected pages are inserted (moved) between the unselected pages. In case of "first" the first selected pages becomes the first page in the result, in case of "second", the first *un*selected page becomes the first page in the result.
Ideally, the selection would be preserved so that the user has good visual feedback.

Every feedback is appreciated. I'm especially unsure about the names of the actions.
