### ISSUE TITLE
What is this repository status ? (was: Create a new release)

### ISSUE THREAD

**Issue by fabaff** [jeromerobert/pdfarranger#9]
Would be nice to have a new release with Python 3 support Thanks.

**Comment by jeromerobert** [comment]
I don't feel in a position to create a release as this is just a mirror repository. The real project is still https://gna.org/projects/pdfshuffler/ and I don't want to fork it unless it die. I created this mirror to:
* use git instead of svn to contribute to pdfshuffler
* give a better visibility of the project (I had to mail Konstantinos Poulios to be aware of the gna.org project).
May be you could try to open a bug on the gna project.

**Comment by stavpup** [comment]
Gna is closing

""Hi,

Gna! has been in maintenance mode for a few years, taking a little
time from Philippe, Vincent and I.

However there are technical upgrades (hardware and software) in the
queue, and neither Vincent nor I feel like spending time on it.

Rather than let the system die until all data is lost or the system is
cracked into, we're considering being honest and shut down the
service, notably the repositories and the mailing lists.  Putting is a
'read-only' could be an option if a technical solution is found, but
probably not.

If people on this list want to do something about it, now is the time
to speak up!  Otherwise we're considering a 6-month notice before
saying goodbye to 13 years of 100%-Free hosting.

(reply to project@xxxxxxx)

Freely,
Sylvain"'

https://mail.gna.org/public/project/2016-11/msg00001.html

**Comment by jeromerobert** [comment]
From <https://sourceforge.net/p/pdfshuffler/feature-requests/36/> the future host will be <https://savannah.nongnu.org/projects/pdfshuffler/> (still no git support)

**Comment by jeromerobert** [comment]
I reopen this issue because the savannah repo is still empty and because of #14

I just e-mailed the original author to known what are is plans

**Comment by jeromerobert** [comment]
I got an answer from logari81 (official dev):

* He remains the developer of pdfshuffler
* Development takes place at https://savannah.nongnu.org/projects/pdfshuffler/
* Source code is now (from several hours ago) available on Savannah (subversion, no git)
* He have no time to work on pdfshuffler for now
* There won't be any 0.7 release soon because he concider pdfshuffler too unstable
* He prefer pdfshuffler to be removed from distros than to release the 0.7 in its current state.
* He accept patches (I guess you have to use the savannah bug tracker for that)

What I'll do:

* Keep using this repo for my own needs (I'll have to switch from `apt-get` to `virtualenv`+`pip`)
* Keep merging logari81 commits in this repo (with a high latency)
* **Not** being the gateway for patch to Savannah
* **Not** being the gateway for issues to Savannah
* **Not** contributing to the pdfshuffler repo on Savannah unless my own needs require it
* Update this repo README

I'll keep this bug open to keep it visible and to avoid duplicates. For further discussion please go to https://savannah.nongnu.org/projects/pdfshuffler/ as logari81 is not reading this repo issues.

**Comment by carlos22** [comment]
Ok but the SF repo seems to be updated, the Savannah is not?!
https://sourceforge.net/p/pdfshuffler/code/HEAD/tree/trunk/ last changed  2018-10-07

**Comment by jeromerobert** [comment]
Yep that's strange. That's the day he uploaded the Savannah repo. Some (all ?) of those 2018-10-07 commits are actually older (see this repo history), but with subversion there no difference between commit date and push date.

**Comment by carlos22** [comment]
For distros it is actually hard to use any forks. If the development is as slow as it was the last 5 years we should consider renaming this fork?!

**Comment by jeromerobert** [comment]
I agree. What about *pdforderer* ?

**Comment by jbicha** [comment]
_PDF Arranger_ ?

**Comment by julianfoad** [comment]
PDF Sorter?

**Comment by jeromerobert** [comment]
PDF sorter seems to already exists (proprietary). PDF Arranger does not but I would prefer *PDF Chou-fleur* (i.e. prononced shoofler and mean cauliflower in french) which is a bit more funny and with no hit in Google. See:
* https://github.com/jeromerobert/pdfshuffler/blob/fork/README.md
* https://github.com/jeromerobert/pdfshuffler/blob/fork/data/hicolor/scalable/apps/pdfchoufleur.svg

**Comment by carlos22** [comment]
Names which sound like the original are funny but hard to google. Also hard to tell non french speaking people?
As a german I would never pronounce it correctly ;-)

**Comment by jeromerobert** [comment]
Ok, then let's go with PDF Arranger.

**Comment by liberforce** [comment]
Just discovered this project by upgrading my Linux distro which silently migrated from pdf-shuffler to pdf-arranger. @jeromerobert : Thanks for trying to keep the project alive, it's very much appreciated. Being French, I also have to acknowledge the pun of wanting to name it "PDF chou-fleur" :1st_place_medal:, gave me a good laugh :smile: . And one more :1st_place_medal: for being reasonable and using a more down-to-earth name (which is always the right choice, as it makes the project more discoverable). Long live PDF Arranger!
