### ISSUE TITLE
expected string or byte-like object error when exporting with pikepdf

### ISSUE THREAD

**Issue by kheaactua** [jeromerobert/pdfarranger#97]
On 5503d73 (in dreua/export_selection), when exporting a selection of pages I received:

> expected string or byte-like object error when exporting selection

![error](https://user-images.githubusercontent.com/2363406/61892230-4af1af00-aed9-11e9-8b6e-6e00cb765154.png)

I only received this on one PDF.  On other PDFs I was able to export selections without issue.

See #95

**Comment by jeromerobert** [comment]
@kheaactua Could you attach the PDF file or make it available somewhere ?

**Comment by kheaactua** [comment]
Here it is.  It's also an interesting article :)

[Why-Most-Unit-Testing-is-Waste.pdf](https://github.com/jeromerobert/pdfarranger/files/3432599/Why-Most-Unit-Testing-is-Waste.pdf)

**Comment by dreua** [comment]
I can confirm that this works with PyPDF2 but not with Pikepdf, export selection or the old fashioned save action makes no difference. TBH I am disappointed, I hoped that Pikepdf would have less errors like these not more :/

@kheaactua In case you didn't know: Pdfarranger uses pikepdf instead of Pypdf2 when it is available. If possible, you can simply uninstall pikepdf (temporarily) and pdfarranger should fall back to Pypdf2 which can handle this file. (I think we should add a switch to make it easier to choose the pdf library.)

**Comment by jeromerobert** [comment]
@dreua I don't want to maintain both pypdf2 and pikepdf, that's why I did not added a switch. Also, I want all that kind of bugs to be reported. I think the workaround for this pikepdf bug will be easy to find and that pikepdf promising. But if after several month of tests, pikepdf appear to be worst that pypdf2, I will remove it.

**Comment by kheaactua** [comment]
@dreua I can give it a try.  Though to be honest that was just a test PDF.  I thought the bug might be an interesting error case though in case it's a general error.  I actually never heard of `pikepdf` or `pypdf2` before this project so really have no opinion. :)  I do know that supporting multiple dependencies is a pain though.

Already this project as is will likely save me tonnes of time with scanning and filing stupid paper work stuff. =D
